### PR TITLE
Add link to patched UniFi firmware info

### PR DESCRIPTION
**Pull request by emdantrim**

### CODE REVIEW

**Comment by emdantrim** [comment]
ah, just realized this is also available further down the page.

**Review by zeadope-zz — CHANGES_REQUESTED** [review]
The [X] link shows up as a new row under the UniFi row.
Please fix. 
(Use https://jbt.github.io/markdown-editor/ to check your changes before committing).

**Comment by emdantrim** [comment]
@zeadope fixed! my bad.

**Comment by kristate** [comment]
Thanks!

**Pull request merged**
