### PR TITLE
Update FreeBSD with announcement

### PR DESCRIPTION
**Pull request by emaste**
I'm looking for confirmation on the "Date notified by CERT" for FreeBSD,
and have annotated it with (?) for now.

### CODE REVIEW

**Comment by vishwin** [comment]
It does not look like FreeBSD was ever notified.
https://lists.freebsd.org/pipermail/freebsd-security/2017-October/009423.html

**Comment by emaste** [comment]
We did have some notice. I believe it is on the order of a few days, not months, but I don't have access to the actual details/mailbox in question.

I thought it's better to just tag the date as questionable than to remove it entirely, while we're trying to find those details: if there is a failing in our response I don't want to appear to be hiding it.

**Comment by vishwin** [comment]
I guess it wasn't a public notice, ie sent to security@. I did see a past CERT notice on security@ but that was from 2002.

**Comment by kristate** [comment]
Went with #54 -- thanks for your help!

**Pull request closed without merging**
