### PR TITLE
Negative results on news/official statement checks

### PR DESCRIPTION
**Pull request by eaglerainbow**
I did some checks on some major companies, whether there was an official statement on the matter recently. For those cases, where I found some things, I created other PRs. 
This PR is the collective summary of those cases, where I could not find anything yet (bumping the "last checked" timestamp)

### CODE REVIEW

**Comment by kristate** [comment]
Thanks for doing this -- can you resolve conflicts/changes?

**Comment by eaglerainbow** [comment]
will do and report back soon

**Comment by eaglerainbow** [comment]
Here we go: Conflicts on the branch has been resolved.
Happy merging 😃

**Comment by kristate** [comment]
Thanks!

**Pull request merged**
