### PR TITLE
Vendor updated page

### PR DESCRIPTION
**Pull request by domenicbrosh**
A list of "Products Possibly Affected" has been added by the vendor.

### CODE REVIEW

**Comment by domenicbrosh** [comment]
D'oh. Sorry for introducing conflicts...

**Comment by kristate** [comment]
Thanks for the info -- if you could resolve the conflicts on your branch (pull from master) and resubmit, that would be wonderful.

**Comment by domenicbrosh** [comment]
*sigh* This is not a graceful resolution, but I don't think I've borked anything.

**Comment by kristate** [comment]
Thanks!

**Pull request merged**
