### PR TITLE
Fix Debian and Ubuntu entries

### PR DESCRIPTION
**Pull request by tyhicks**
Ubuntu stable update information differs from Debian stable update information. Additionally, it would be best to point to Debian's security advisory rather than to the bugtraq thread.

### CODE REVIEW

**Comment by kristate** [comment]
Agreed -- thanks!

**Comment by lode** [comment]
This change seems lost since https://github.com/kristate/krackinfo/commit/b0dbbc9490e6d6f257af2bfd03b4762abb3e6106

**Comment by tyhicks** [comment]
@kristate can you fix up that bad merge commit or would you like me to?

**Comment by tyhicks** [comment]
I've submitted https://github.com/kristate/krackinfo/pull/47 for the issue that @lode spotted.

**Pull request merged**
